version: "3"

services:
  fe:
    image: culture4web/culture-web-fe:v1.0.0
    networks:
      - app-network

  be:
    image: culture4web/culture-web-be:v1.0.0
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - fe
      - be
      - char-recognition
    networks:
      - app-network

  char-recognition:
    image: culture4web/culture-web-microservices:char-recognition_v1.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
