version: "3"

services:
  fe:
    image: culture4web/culture-web-fe:v2.7.0
    networks:
      - app-network

  be:
    image: culture4web/culture-web-be:v2.8.0
    depends_on:
      - local-postgres
      - minio
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - fe
      - be
      - char-recognition
      - expression-recognition
    networks:
      - app-network

  char-recognition:
    image: culture4web/culture-web-microservices:char-recognition_v2.1.0
    networks:
      - app-network

  expression-recognition:
    image: culture4web/culture-web-microservices:expression-recognition_v2.1.0
    networks:
      - app-network
  
  face-detection:
    image: culture4web/culture-web-microservices:face-detection_v2.1.0
    networks:
      - app-network

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    restart: unless-stopped
    
  local-postgres:
    image: pgvector/pgvector:pg16
    container_name: local-postgres
    environment:
      - POSTGRES_USER=${LOCAL_DB_USER}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_DB=${LOCAL_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init/local_rag_setup.sql:/docker-entrypoint-initdb.d/local_rag_setup.sql:ro
      - ./init/init.sh:/docker-entrypoint-initdb.d/99-init.sh:ro
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  local_pgdata:
  minio_data:
