services:
  fe:
    image: culture4web/culture-web-fe:latest
    ports:
      - "80:80"

  be:
    image: culture4web/culture-web-be:latest

  char-recognition:
    image: culture4web/culture-web-microservices:char-recognition_latest
