version: "3"

services:
  fe:
    image: culture4web/culture-web-fe:v2.6.0
    networks:
      - app-network

  be:
    image: culture4web/culture-web-be:v2.7.0
    volumes:
      - ../culture-web-be/uploads:/uploads
    depends_on:
      - local-postgres      
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - fe
      - be
      - char-recognition
      - expression-recognition
    networks:
      - app-network

  char-recognition:
    image: culture4web/culture-web-microservices:char-recognition_v2.1.0
    networks:
      - app-network

  expression-recognition:
    image: culture4web/culture-web-microservices:expression-recognition_v2.1.0
    networks:
      - app-network
  
  face-detection:
    image: culture4web/culture-web-microservices:face-detection_v2.1.0
    networks:
      - app-network
    
  local-postgres:
    image: pgvector/pgvector:pg16
    container_name: local-postgres
    environment:
      - POSTGRES_USER=${LOCAL_DB_USER}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_DB=${LOCAL_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init/local_rag_setup.sql:/docker-entrypoint-initdb.d/local_rag_setup.sql:ro
      - ./init/init.sh:/docker-entrypoint-initdb.d/99-init.sh:ro
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  local_pgdata:
