version: "3"

services:
  fe:
    image: culture4web/culture-web-fe:v1.0.0
    networks:
      - app-network

  be:
    image: culture4web/culture-web-be:v1.0.0
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - fe
      - be
      - char-recognition
      - expression-recognition
      - face-detection
    networks:
      - app-network

  char-recognition:
    image: culture4web/culture-web-microservices:char-recognition_dev-latest
    networks:
      - app-network

  expression-recognition:
    image: culture4web/culture-web-microservices:expression-recognition_dev-latest
    networks:
      - app-network

  face-detection:
    image: culture4web/culture-web-microservices:face-detection_dev-latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
